# Fly.io configuration for DDSP Neural Cello
# embracingearth.space

app = "ddsp"  # Change this to your unique name
primary_region = "iad"

[build]

[env]
  PORT = "8000"
  MODEL_PATH = "./models"
  OUTPUT_PATH = "./output"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024  # Increased for audio processing workloads

# Persistent storage for models (uploaded models persist across deployments)
[[mounts]]
  source = "model_storage"
  destination = "/app/models"

