# Fly.io configuration for DDSP Neural Cello
# embracingearth.space

app = "ddsp"
primary_region = "iad"

[build]
  # Explicitly use Docker build - this is a Python app, not Next.js
  # Force Docker build to prevent Next.js auto-detection
  dockerfile = "Dockerfile"
  buildargs = []
  ignorefile = ".dockerignore"
  
[deploy]
  strategy = "immediate"
  # Release command is not needed - we run Python directly

[env]
  PORT = "8000"
  MODEL_PATH = "./models"
  OUTPUT_PATH = "./output"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024  # Increased for audio processing workloads

# Persistent storage for models (uploaded models persist across deployments)
[[mounts]]
  source = "model_storage"
  destination = "/data/models"

